README.md
=> add missing comma in readme.md

src/ComposerEventHandler.php
=> create output directory for merge_plan

tests/Integration/ComposerEventHandlerTest.php, tests/Packages/first-vendor/first-package/composer.json
=> Splitting init in tests

src/ComposerEventHandler.php, tests/.gitignore, tests/Integration/ComposerEventHandlerTest.php, tests/Integration/ComposerTest.php, tests/Packages/first-vendor/first-package-1.0.1/composer.json, tests/Packages/first-vendor/first-package-1.0.1/config/constants.php, tests/Packages/first-vendor/first-package-1.0.1/config/params.php, tests/Packages/first-vendor/first-package-1.0.2-changed-config/composer.json, tests/Packages/first-vendor/first-package-1.0.2-changed-config/config/constants.php, tests/Packages/first-vendor/first-package-1.0.2-changed-config/config/params.php, tests/Packages/first-vendor/first-package-1.0.3-changed-config/composer.json, tests/Packages/first-vendor/first-package-1.0.3-changed-config/config/constants.php, tests/Packages/first-vendor/first-package-1.0.3-changed-config/config/params.php, tests/Packages/first-vendor/first-package-1.0.4/composer.json, tests/Packages/first-vendor/first-package-1.0.4/config/constants.php, tests/Packages/first-vendor/first-package-1.0.4/config/params.php, tests/Packages/second-vendor/second-package-1.0.1-changed-config/composer.json, tests/Packages/second-vendor/second-package-1.0.1-changed-config/config/params.php, tests/Packages/second-vendor/second-package/composer.json, tests/Packages/second-vendor/second-package/config/params.php
| Fixed issues  | #3 
Adopt PRs:
| Package             | PR
| `yiisoft/app`    | https://github.com/yiisoft/app/pull/135
| `yiisoft/yii-demo`    | https://github.com/yiisoft/yii-demo/pull/254
| `yiisoft/app-api`    | https://github.com/yiisoft/app-api/pull/51
| `yiisoft/demo-api`    | https://github.com/yiisoft/demo-api/pull/14
| `yiisoft/yii-console`    | https://github.com/yiisoft/yii-console/pull/106
| `yiisoft/view`    | https://github.com/yiisoft/view/pull/129
| `yiisoft/yii-event`    | https://github.com/yiisoft/yii-event/pull/24
=> Implement config updates

src/ComposerEventHandler.php
=> Fix: output dir

src/ComposerEventHandler.php, tests/Integration/ComposerEventHandlerTest.php
=> Remove update when user config didn't change

src/ComposerEventHandler.php, src/PackagesListBuilder.php, tests/Integration/PackagesListBuilderTest.php, tests/Packages/test/a/composer.json, tests/Packages/test/a/config/params.php, tests/Packages/test/a/config/web.php, tests/Packages/test/ba/composer.json, tests/Packages/test/ba/config/web.php, tests/Packages/test/c/composer.json, tests/Packages/test/c/config/params.php, tests/Packages/test/c/config/web.php
=> Build packages list with their dependencies and depth in mind

src/ComposerEventHandler.php, src/Options.php, tests/Integration/PackagesListBuilderTest.php, tests/Integration/PackagesListBuilderWithSourceDirectoryTest.php, tests/Integration/SourceDirectoryTest.php, tests/Packages/test/custom-source/composer.json, tests/Packages/test/custom-source/custom-dir/params.php, tests/Packages/test/custom-source/custom-dir/web.php, tests/Unit/OptionsTest.php
=> Add option "source-directory"

src/ComposerEventHandler.php, src/Options.php, tests/Integration/ForceCheckTest.php, tests/Unit/OptionsTest.php
=> Add option "force-check"

src/ComposerEventHandler.php, tests/Integration/PackagesListBuilderWithVariablesTest.php
=> Fix: root package don't support variables.

composer.json, src/ComposerEventHandler.php, tests/Integration/ForceCheckTest.php
=> Force check all config files on install or update yiisoft/config

src/ComposerEventHandler.php, src/ConfigFileHandler.php, tests/Integration/MessagesTest.php, tests/Unit/ConfigFileHandlerTest.php, tests/Unit/TestCase.php
=> Fix create-project, disable default choice, add choices title

src/Config.php, tests/Unit/ComposerConfigProcessTest.php, tests/Unit/ComposerEventHandlerTest.php, tests/Unit/ConfigFileHandlerTest.php, tests/Unit/ConfigFileUpdaterTest.php, tests/Unit/ConfigTest.php, tests/Unit/TestCase.php, tests/configs/dummy/config/common/1.php, tests/configs/dummy/config/common/2.php, tests/configs/dummy/config/packages/merge_plan.php, tests/configs/dummy/config/packages/test/a/common.php, tests/configs/dummy/config/packages/test/a/params.php, tests/configs/dummy/config/packages/test/a/web.php, tests/configs/dummy/config/packages/test/b/common.php, tests/configs/dummy/config/packages/test/b/params.php, tests/configs/dummy/config/packages/test/b/web.php, tests/configs/dummy/config/params-local.php, tests/configs/dummy/config/params.php, tests/configs/dummy/config/web.php
=> Add unit test cases for code coverage

src/Config.php, tests/Unit/ConfigTest.php, tests/configs/dummy/config/alfa/main.php, tests/configs/dummy/config/alfa/params.php, tests/configs/dummy/config/alfa/web.php, tests/configs/dummy/config/beta/events.php, tests/configs/dummy/config/environment/main.php, tests/configs/dummy/config/environment/params.php, tests/configs/dummy/config/environment/web.php, tests/configs/dummy/config/events.php, tests/configs/dummy/config/packages/merge_plan.php
=> Fix environment variable handling to Config class

src/Config.php, tests/Unit/ConfigTest.php, tests/configs/dummy/config/beta/params.php, tests/configs/dummy/config/beta/web.php, tests/configs/dummy/config/packages/merge_plan.php
=> Remove pass of config object to parameters file

src/ConfigFileHandler.php, src/ConfigFileUpdater.php, tests/Unit/ConfigFileUpdaterTest.php
=> Fix remove package metadata from dist.lock

README.md
=> Add description of use of environments and update readme

README.md, composer.json
=> Remove support for first version of composer

README.md, src/Config.php, tests/Unit/ConfigTest.php
| Breaks BC?    | ✔️
- https://github.com/yiisoft/app/pull/181
- https://github.com/yiisoft/app-api/pull/90
- https://github.com/yiisoft/demo/pull/334
- https://github.com/yiisoft/demo-api/pull/45
=> Optional recursive merge

.scrutinizer.yml, src/Config.php, tests/Unit/ConfigTest.php, tests/configs/dummy/config/common/nested/1.php, tests/configs/dummy/config/common/nested/2.php, tests/configs/dummy/config/packages/merge_plan.php
=> Add a test case for patterns of nested configuration files

README.md, src/Config.php, src/Context.php, src/FilesExtractor.php, src/Merger.php, src/Modifier/RemoveFromVendor.php, src/Modifier/RemoveGroupsFromVendor.php, src/Modifier/RemoveKeysFromVendor.php, tests/ConfigTest.php, tests/Modifier/RemoveKeysFromVendorTest.php, tests/TestAsset/configs/remove-from-vendor-packages/config/.merge-plan.php, tests/TestAsset/configs/remove-from-vendor-packages/config/params.php, tests/TestAsset/configs/remove-from-vendor-packages/config/params1.php, tests/TestAsset/configs/remove-from-vendor-packages/config/params2.php, tests/TestAsset/configs/remove-from-vendor-packages/vendor/package/a/params1.php, tests/TestAsset/configs/remove-from-vendor-packages/vendor/package/a/params2.php, tests/TestAsset/configs/remove-from-vendor-packages/vendor/package/b/params1.php, tests/TestAsset/configs/remove-from-vendor-packages/vendor/package/b/params2.php
=> Add modifier `RemoveFromVendor::groups()` and add ability specify groups in `RemoveFromVendor::keys()`

src/Composer/MergePlanProcess.php, src/Options.php, tests/Composer/MergePlanProcessTest.php, tests/Composer/TestCase.php, tests/OptionsTest.php
=> Add build of merge plan option

README.md, src/Modifier/RemoveFromVendor.php
=> Replace yiisoft/yii-web to yiisoft/view in documentation examples

tests/Composer/TestCase.php, tests/ConfigTest.php, tests/TestAsset/configs/dummy/config/.merge-plan.php
=> Check addition config group without configs

README.md, src/Config.php, src/FilesExtractor.php, tests/ConfigTest.php
=> Add Config::has() method

.gitattributes, roave-bc-check.yaml
=> Add ignoring BC errors about composer/composer package not found

.github/workflows/mutation.yml, CHANGELOG.md, src/Config.php, src/ConfigInterface.php
=> Add ConfigInterface

CHANGELOG.md, src/Merger.php, tests/ConfigTest.php
=> Improve error message by displaying group name

src/Command/CopyCommand.php, src/Composer/MergePlanProcess.php, src/Composer/PackagesListBuilder.php, src/Composer/ProcessHelper.php, tests/Composer/EventHandlerTest.php, tests/Composer/TestCase.php, tests/ConfigPathsTest.php, tests/ConfigTest.php
| Readability fix  | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines.
=> Separate chain calls

CHANGELOG.md, src/DataModifiers.php, tests/Composer/TestCase.php
=> Optimize array_merge

composer.json, psalm.xml
=> Improve psalm config

.editorconfig, CHANGELOG.md, README.md, src/Composer/MergePlanProcess.php, src/Composer/ProcessHelper.php, src/Config.php, src/Options.php, tests/Composer/MergePlanProcessTest.php, tests/Composer/TestCase.php, tests/ConfigTest.php, tests/TestAsset/configs/custom-merge-plan-file/config/params.php, tests/TestAsset/configs/custom-merge-plan-file/config/web.php, tests/TestAsset/configs/custom-merge-plan-file/merge-plan.php, tests/TestAsset/configs/custom-merge-plan-file/vendor/package/a/params.php, tests/TestAsset/configs/custom-merge-plan-file/vendor/package/a/web.php, tests/TestAsset/configs/custom-merge-plan-file/vendor/package/b/params.php, tests/TestAsset/configs/custom-merge-plan-file/vendor/package/b/web.php, tests/runtime/.gitignore
=> Add ability to change merge plan filepath

README.md
=> Add note to "Environment" section of readme

CHANGELOG.md, src/Composer/PackagesListBuilder.php, src/Composer/ProcessHelper.php, tests/Composer/TestCase.php, tests/TestAsset/packages/metapack/composer.json
=> Use composer library and plugins only

composer.json
=> Remove suggestions from `composer.json` and add `bump-after-update` option
